<a href="https://colab.research.google.com/github/victoricoma/am-t4-s1a2026/blob/main/Aula0428API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import requests
import pandas as pd

url = 'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=IBM&interval=5min&apikey=6OIWZMVDR987T4G2'
r = requests.get(url)
base = r.json()

In [6]:
base_alpha = pd.DataFrame.from_dict(base['Time Series (Daily)'], orient='index')
base_alpha = base_alpha.transpose()
base_alpha

,2026-04-27,2026-04-24,2026-04-23,2026-04-22,2026-04-21,2026-04-20,2026-04-17,2026-04-16,2026-04-15,2026-04-14,...,2025-12-15,2025-12-12,2025-12-11,2025-12-10,2025-12-09,2025-12-08,2025-12-05,2025-12-04,2025-12-03,2025-12-02
1. open,229.9500,231.9300,232.2700,254.5100,254.0000,255.0000,254.6700,248.7500,242.2500,238.7500,...,308.9850,310.5700,312.0000,310.2300,309.6300,309.6200,308.5900,302.8750,302.8800,307.0000
2. high,231.3200,232.7999,232.9100,257.5400,258.0900,258.5000,255.6500,251.2200,246.0600,241.5375,...,311.3629,311.0500,313.4400,314.6900,313.9700,315.3454,311.8300,309.6100,303.9700,310.4675
3. low,227.1200,225.0000,221.7300,247.2100,251.8650,252.5600,251.0400,246.1250,240.9850,238.1200,...,306.3500,303.3300,308.4000,306.6513,308.7500,307.9500,307.1800,302.5400,298.9050,301.5700
4. close,228.0500,231.9800,231.0800,251.8600,255.6800,253.7100,253.4700,251.0000,244.8000,240.2700,...,308.6600,309.2400,310.7400,312.6700,310.4800,309.1800,307.9400,307.9900,302.6200,301.7800
5. volume,8060665,9816859,22297831,12190197,5584901,5157714,5671471,4817500,3879518,3777272,...,3566732,2953374,2755749,3411524,2914275,3615794,2344667,2962463,3953390,4261100

In [7]:
base_alpha=base_alpha.T

In [8]:
base_alpha

             1. open   2. high    3. low  4. close 5. volume
2026-04-27  229.9500  231.3200  227.1200  228.0500   8060665
2026-04-24  231.9300  232.7999  225.0000  231.9800   9816859
2026-04-23  232.2700  232.9100  221.7300  231.0800  22297831
2026-04-22  254.5100  257.5400  247.2100  251.8600  12190197
2026-04-21  254.0000  258.0900  251.8650  255.6800   5584901
...              ...       ...       ...       ...       ...
2025-12-08  309.6200  315.3454  307.9500  309.1800   3615794
2025-12-05  308.5900  311.8300  307.1800  307.9400   2344667
2025-12-04  302.8750  309.6100  302.5400  307.9900   2962463
2025-12-03  302.8800  303.9700  298.9050  302.6200   3953390
2025-12-02  307.0000  310.4675  301.5700  301.7800   4261100

[100 rows x 5 columns]

In [9]:
import numpy as np

In [10]:
base_alpha_num = base_alpha.astype(float)

In [12]:
base_alpha_num['target'] = (base_alpha_num['4. close'].shift(-1) > base_alpha_num['4. close'])
base_alpha_num.dropna(inplace=True)

In [13]:
base_alpha_num

            1. open   2. high   3. low  4. close   5. volume  target
2026-04-27  229.950  231.3200  227.120    228.05   8060665.0    True
2026-04-24  231.930  232.7999  225.000    231.98   9816859.0   False
2026-04-23  232.270  232.9100  221.730    231.08  22297831.0    True
2026-04-22  254.510  257.5400  247.210    251.86  12190197.0    True
2026-04-21  254.000  258.0900  251.865    255.68   5584901.0   False
...             ...       ...      ...       ...         ...     ...
2025-12-08  309.620  315.3454  307.950    309.18   3615794.0   False
2025-12-05  308.590  311.8300  307.180    307.94   2344667.0    True
2025-12-04  302.875  309.6100  302.540    307.99   2962463.0   False
2025-12-03  302.880  303.9700  298.905    302.62   3953390.0   False
2025-12-02  307.000  310.4675  301.570    301.78   4261100.0   False

[100 rows x 6 columns]

In [14]:
base_alpha_reg = base_alpha.astype(float)

In [16]:
base_alpha_reg['6. target_reg'] = base_alpha_reg['4. close'].pct_change().shift(-1)

In [17]:
base_alpha_reg

            1. open   2. high   3. low  4. close   5. volume  6. target_reg
2026-04-27  229.950  231.3200  227.120    228.05   8060665.0       0.017233
2026-04-24  231.930  232.7999  225.000    231.98   9816859.0      -0.003880
2026-04-23  232.270  232.9100  221.730    231.08  22297831.0       0.089926
2026-04-22  254.510  257.5400  247.210    251.86  12190197.0       0.015167
2026-04-21  254.000  258.0900  251.865    255.68   5584901.0      -0.007705
...             ...       ...      ...       ...         ...            ...
2025-12-08  309.620  315.3454  307.950    309.18   3615794.0      -0.004011
2025-12-05  308.590  311.8300  307.180    307.94   2344667.0       0.000162
2025-12-04  302.875  309.6100  302.540    307.99   2962463.0      -0.017436
2025-12-03  302.880  303.9700  298.905    302.62   3953390.0      -0.002776
2025-12-02  307.000  310.4675  301.570    301.78   4261100.0            NaN

[100 rows x 6 columns]

In [18]:
base_alpha_med = base_alpha.astype(float)

In [21]:
base_alpha_med['6. avg'] = base_alpha_med['4. close'].rolling(window=3).mean().shift(-3)

In [22]:
base_alpha_med

            1. open   2. high   3. low  4. close   5. volume      6. avg
2026-04-27  229.950  231.3200  227.120    228.05   8060665.0  238.306667
2026-04-24  231.930  232.7999  225.000    231.98   9816859.0  246.206667
2026-04-23  232.270  232.9100  221.730    231.08  22297831.0  253.750000
2026-04-22  254.510  257.5400  247.210    251.86  12190197.0  254.286667
2026-04-21  254.000  258.0900  251.865    255.68   5584901.0  252.726667
...             ...       ...      ...       ...         ...         ...
2025-12-08  309.620  315.3454  307.950    309.18   3615794.0  306.183333
2025-12-05  308.590  311.8300  307.180    307.94   2344667.0  304.130000
2025-12-04  302.875  309.6100  302.540    307.99   2962463.0         NaN
2025-12-03  302.880  303.9700  298.905    302.62   3953390.0         NaN
2025-12-02  307.000  310.4675  301.570    301.78   4261100.0         NaN

[100 rows x 6 columns]

In [23]:
base_alpha_med['7. trend'] = (base_alpha_med['6. avg'] > base_alpha_med['4. close']).astype(int)

In [24]:
base_alpha_med

,1. open,2. high,3. low,4. close,5. volume,6. avg,7. trend
2026-04-27,229.950,231.3200,227.120,228.05,8060665.0,238.306667,1
2026-04-24,231.930,232.7999,225.000,231.98,9816859.0,246.206667,1
2026-04-23,232.270,232.9100,221.730,231.08,22297831.0,253.750000,1
2026-04-22,254.510,257.5400,247.210,251.86,12190197.0,254.286667,1
2026-04-21,254.000,258.0900,251.865,255.68,5584901.0,252.726667,0
...,...,...,...,...,...,...,...
2025-12-08,309.620,315.3454,307.950,309.18,3615794.0,306.183333,0
2025-12-05,308.590,311.8300,307.180,307.94,2344667.0,304.130000,0
2025-12-04,302.875,309.6100,302.540,307.99,2962463.0,NaN,0
2025-12-03,302.880,303.9700,298.905,302.62,3953390.0,NaN,0
2025-12-02,307.000,310.4675,301.570,301.78,4261100.0,NaN,0